### ISSUE TITLE
URP in 2021.1

### ISSUE THREAD

**Issue by WeaselKing** [ExtendRealityLtd/Tilia.Locomotors.Teleporter.Unity#63] opened 2021-05-26 16:22 UTC
### Environment

* Code source:  CameraColorOverlay.cs
* Code version: 1.6.2
* Platform version: Windows 10
* 3rd party dependencies: None

### Steps to reproduce

Attempt to make the Add Transitioned event in Camera Color Overlay do something.

### Expected behavior

The method you put in that event should fire after rendering has completed and the screen has been blacked out.

### Current behavior

The method does not fire. It is depending on Camera.onPostRender to fire, which no longer fires once the screen has been rendered in URP. Unity doesn't give any errors or indicators that it no longer does anything, it just silently fails, now.

I think it needs a similar fix to the one that was put into momentprocessor.cs in the OnPreRender event to make that one work.

**Comment by thestonefox** [comment] 2021-05-26 16:26
the fade wont work in URP because the logic isn't compatible with URP.

this is a duplicate of https://github.com/ExtendRealityLtd/Zinnia.Unity/issues/481

**Closed by thestonefox** 2021-05-26 16:26 UTC
